sudo: required
services:
    - docker

before_install:
    - docker build -t askaravskiy/myapp-web-client -f Dockerfile.dev .

script:
    - docker run askaravskiy/myapp-web-client npm run test

after_success:
    - docker build -t askaravskiy/myapp-web-client .
    - docker build -t askaravskiy/myapp-web-nginx ./nginx
    - docker build -t askaravskiy/myapp-web-server ./server
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Take those images and push them to docker hub
    - docker push askaravskiy/myapp-web-client
    - docker push askaravskiy/myapp-web-nginx
    - docker push askaravskiy/myapp-web-server

#deploy:
#    provider: elasticbeanstalk
#    region: us-east-2
#    app: myApp-web
#    env: Myappweb-env
#    bucket_name: 'elasticbeanstalk-us-east-2-865284307270'
#    bucket_path: 'my-app-web'
#    on:
#        branch: main
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY

deploy:
  provider: heroku